import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getSortedPostsData } from '../lib/posts';

export type ThenArg<T> = T extends PromiseLike<infer U> ? U : T;

export async function getStaticProps() {
  const allPostsData = getSortedPostsData() as {
    id: string;
    date: string;
    title: string
  }[];

  return {
    props: {
      allPostsData,
    },
  };
}

const Home = ({ allPostsData }: ThenArg<ReturnType<typeof getStaticProps>>['props']) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <h2>Blog</h2>
          <ul>
            {(allPostsData || []).map(({ id, date, title }) => (
              <li key={id}>
                {title}
                <br />
                {id}
                <br />
                {date}
              </li>
            ))}
          </ul>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
